export interface IZadaci {
    ZAD_ID: number,
    CTRL_FORME: string,
    D_EKRANSKI_IZGLED1: string,
    D_EKRANSKI_IZGLED2: string,
    D_FUN_SPEC: string,
    D_IZVESTAJ_SPEC: string,
    D_NAZIV_POGLAVLJA: string,
    D_NAZIV_POGLAVLJA_NAD: string,
    D_OPIS_POGLAVLJA: string,
    D_OPIS_POGLAVLJA_NAD: string,
    D_RBR_PRIKAZA: number,
    D_STAMPA_SPEC: string,
    DATUM_AZURNO: Date,
    ID_AKTIVAN: number,
    IND_NAVIGACIJA: number,
    NADREDJENI_ZAD: number,
    NAZIV_ZAD: string,
    NAZIV_ZAD_KRATKO: string,
    RED_PRIKAZA: number,
    STATE_FORME: string,
    TOOLTIP: string,
    URL_FORME: string,
    ZAD_ID_OLD: number
}